version: '3.8'

services:
  mariadb:
    build:
      context: ./src/requirements/Mariadb
      dockerfile: Dockerfile
    env_file:
      - src/.env
    ports:
     - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    image: mariadb
    container_name: mariadb 


  nginx:
    build: ./src/requirements/NGINX
    #dockerfile: Dockerfile
    ports:
      - "8443:8443"
    volumes:
      - ./src/requirements/NGINX/conf/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - wordpress
    image: nginx
    container_name: nginx

  wordpress:
    build: 
      context: ./src/requirements/WordPress
      dockerfile: Dockerfile
    env_file:
      - src/.env
    volumes:
      - ./src/requirements/conf/www.conf:/var/www/html
    depends_on:
      - mariadb
    ports:
      - "9000:9000"
    image: wordpress
    container_name: wordpress
    restart: always

volumes:
  mariadb_data: